### ISSUE TITLE
GET /wiki/docs runs into a timeout

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/MultiWikiServer#35]
OS: Ubuntu 24.04.1
node 22.12.0
Installation using: [How to run](https://github.com/TiddlyWiki/MultiWikiServer?tab=readme-ov-file#how-to-run)

mws-docs, dev-docs and tour can be loaded. But mws-docs needs close to 1 second to load. Seems to be a bit slow. 

GET /wiki/docs seems to runs into a timeout.

```
GET /wiki/docs
https://localhost:5000/wiki/docs PrismaClientKnownRequestError:
Invalid `prisma.recipe_bags.findFirst()` invocation:


Transaction API error: Transaction already closed: A query cannot be executed on an expired transaction. The timeout for this transaction was 5000 ms, however 5000 ms passed since the start of the transaction. Consider increasing the interactive transaction timeout or doing less work in the transaction.
    at Un.handleRequestError (/home/mario/mws/node_modules/@prisma/client/runtime/library.js:121:7447)
    at Un.handleAndLogRequestError (/home/mario/mws/node_modules/@prisma/client/runtime/library.js:121:6771)
    at Un.request (/home/mario/mws/node_modules/@prisma/client/runtime/library.js:121:6478)
    at l (/home/mario/mws/node_modules/@prisma/client/runtime/library.js:130:9644)
    at _TiddlerServer.getRecipeBagWithTiddler (file:///home/mario/mws/node_modules/@tiddlywiki/mws/src/routes/TiddlerStore.ts:328:12)
    at _TiddlerServer.getRecipeTiddler (file:///home/mario/mws/node_modules/@tiddlywiki/mws/src/routes/TiddlerStore.ts:317:24)
    at _TiddlerServer.serveIndexFile (file:///home/mario/mws/node_modules/@tiddlywiki/mws/src/routes/bag-file-server.ts:266:20)
    at file:///home/mario/mws/node_modules/@tiddlywiki/mws/src/routes/managers/router-tiddlers.ts:259:9
    at Proxy._transactionWithCallback (/home/mario/mws/node_modules/@prisma/client/runtime/library.js:130:8005)
    at Proxy.$transaction (file:///home/mario/mws/node_modules/@tiddlywiki/mws/src/StateObject.ts:126:12) {
  code: 'P2028',
  clientVersion: '6.4.1',
  meta: {
    modelName: 'Recipe_bags',
    error: 'Transaction already closed: A query cannot be executed on an expired transaction. The timeout for this transaction was 5000 ms, however 5000 ms passed since the start of the transaction. Consider increasing the interactive transaction timeout or doing less work in the transaction.'
  }
}
```

**Comment by Arlen22** [comment]
I fixed this with https://github.com/TiddlyWiki/MultiWikiServer/commit/65f256dd97ee745b7b51fe386cf3b685bc60e0a7

The problem was basically that the old version of mws was doing one database call per tiddler, which wasn't nearly as big a deal when it was synchronous. I've managed to reduce it to a single prisma query for the entire request.

**Comment by pmario** [comment]
Will be able to test next week

**Comment by pmario** [comment]
This one seems to work now using WLS 2 

Still can't start it with Windows. See [Talk feedback](https://talk.tiddlywiki.org/t/mws-installation-errors/10746/34?u=pmario).
